//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD_BlogProject_2021.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Abouts
    {
        public int AboutId { get; set; }
        public string Title { get; set; }

        [AllowHtml]
        public string Description { get; set; }
    }
}
