//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD_BlogProject_2021.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resumes
    {
        public int ResumeId { get; set; }
        public string ResumeTitle { get; set; }
        public string ResumeSubTitle { get; set; }
        public string ResumePlace { get; set; }
        public System.DateTime ResumeDate { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public bool IsActive { get; set; }
    }
}
